/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_L_PR_Idea_OrganisationTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_L_PR_Idea_OrganisationTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new L_PR_Idea_Organisation__c());
    }
}