/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_L_PR_External_Org_Opportunita3OTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_L_PR_External_Org_Opportua3OTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new L_PR_External_Org_Opportunity_Relation__c());
    }
}